language: go
sudo: required

before_install:
  - mkdir -p $GOPATH/src/github.com/zeebe-io
  - cd $GOPATH/src/github.com/zeebe-io
  - git clone https://github.com/zeebe-io/zbc-go.git
  - cd zbc-go
  - git checkout 0.7.0
  - cd $GOPATH/src/github.com/holunda-io/zeebe-go-spencer

script: go build -v ./...