version: '2'

services:
  zeebe:
    image: camunda/zeebe:latest
    environment:
        - ZEEBE_LOG_LEVEL=debug
        - ZEEBE_HOST=zeebe
    ports:
      - "51015:51015"
      - "51016:51016"
      - "51017:51017"

  mainapp:
    image: mainapp
    environment:
      - ZEEBE_HOST=zeebe
    ports:
      - "8080:8080"
    depends_on:
      - zeebe

  hero1:
    image: heroapp
    environment:
      - HERO=b
      - ZEEBE_HOST=zeebe
    depends_on:
      - zeebe
      - mainapp

  hero2:
    image: heroapp
    environment:
      - HERO=t
      - ZEEBE_HOST=zeebe
    depends_on:
      - zeebe
      - mainapp

  hero3:
    image: heroapp
    environment:
      - HERO=h7
      - ZEEBE_HOST=zeebe
    depends_on:
      - zeebe
      - mainapp

  monitor:
    image: camunda/zeebe-simple-monitor
    depends_on:
      - zeebe
    ports:
      - "9080:8080"
